# -*- coding: utf-8 -*-
"""Add 2026 nail-trend novelties into nails-data.json and catalog.json."""
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "public" / "nails" / "nails-data.json"
CATALOG = ROOT / "public" / "nails" / "catalog.json"
ADDED = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")

DESIGNS = [
    {
        "n": 111,
        "description": "Новинка 2026: ювелирный френч — молочная база и кончики, осыпанные мелкими кристаллами, как будто кончики окунули в бокал с блёстками. Маникюр ловит свет при каждом движении руки и выглядит как тонкое украшение, а не «стразы с витрины».",
        "colors": ["молочный", "нюд", "серебряный", "прозрачный"],
        "style": "гламурный френч",
        "tags": ["френч 2026", "стразы", "ювелирный френч", "новинка", "вечерний"],
        "color": "молочный",
        "complexity": "сложно",
        "shape": "миндаль",
        "length": "длинные",
        "techniques": ["френч", "инкрустация", "гель-клей для кристаллов", "молочная база"],
        "design_category": "ювелирный френч",
        "timeMinutes": 120,
        "masterGuide": "\n".join([
            "1. Подготовьте пластину, придайте длинную миндалевидную форму, выровняйте кутикулу.",
            "2. Укрепите и выровняйте базой, просушите.",
            "3. Нанесите молочно-нюдовый гель-лак в 2 тонких слоя, каждый слой просушите.",
            "4. Тонкой кистью выведите очень чёткую линию улыбки молочным или полупрозрачным гелем.",
            "5. На ещё слегка липкий кончик точечно нанесите профессиональный клей для кристаллов — не сажайте стразы в сырой гель-лак.",
            "6. Выложите мелкие кристаллы и серебряные кафиры плотным рядом по линии улыбки, крупные камни — только 1–2 на акцентном пальце.",
            "7. Просушите, затем каплей густого геля «запечатайте» каждый камень у основания.",
            "8. Перекройте топом без липкого слоя всю свободную поверхность, обходя грани кристаллов.",
            "9. Пройдите торцы, чтобы инкрустация не цеплялась за одежду.",
            "10. Нанесите масло на кутикулу: кожа должна выглядеть влажной и ухоженной.",
        ]),
        "prompt": "Ultra-photoreal salon manicure, long almond nails. Milky nude glossy gel base with a crisp French smile line. The tips are densely set with tiny high-end rhinestones and silver caviar beads like jewelry, catching softbox light. Perfectly moisturized cuticles, even nail beds, no dry skin. Macro beauty campaign of one real woman's hand, five fingers only.",
    },
    {
        "n": 112,
        "description": "Тренд подиума SS26: «носки атлета» и пинстрайп. Белая глянцевая подложка и две тонкие горизонтальные красные полоски у свободного края — графично, спортивно и очень чисто. Выглядит дорого именно за счёт ровных линий, а не обилия декора.",
        "colors": ["белый", "красный", "молочный"],
        "style": "графичный минимализм",
        "tags": ["пинстрайп", "полоски", "подиум 2026", "спортивный френч", "новинка"],
        "color": "белый",
        "complexity": "средне",
        "shape": "миндаль",
        "length": "длинные",
        "techniques": ["стрипинг", "горизонтальные линии", "глянцевый топ"],
        "design_category": "пинстрайп",
        "timeMinutes": 75,
        "masterGuide": "\n".join([
            "1. Длинный миндаль, идеально ровный свободный край.",
            "2. База + выравнивание, просушка.",
            "3. Два плотных слоя белого или молочно-белого гель-лака, каждый просушить.",
            "4. Глянцевый топ без липкого слоя — полоски лягут чётче.",
            "5. Стриперной кистью или тонкой лентой наметьте две параллельные красные линии у свободного края, как на спортивном носке.",
            "6. Расстояние между линиями одинаковое на всех пальцах, толщина волосяная, без дрожания.",
            "7. Просушите красный гель-лак 30–60 секунд.",
            "8. Перекройте тонким топом, не размазывая линии.",
            "9. Запечатайте торцы.",
            "10. Масло на кутикулу, уберите пыль с боковых валиков.",
        ]),
        "prompt": "Ultra-photoreal salon manicure, long almond nails. Glossy opaque white gel with two ultra-thin parallel horizontal red pinstripes near each free edge, athletic-sock French, SS26 runway. Perfectly even lines, groomed moisturized hands, no extra nail art. Macro beauty photo, five real fingers.",
    },
    {
        "n": 113,
        "description": "Чёрный глянец с «пирсингом» ногтя: мини-кольцо из жёлтого золота проходит сквозь длинный ноготь у свободного края. Жёсткий, модный жест 2026 года — как серьга, только на кончике. Смотрится остро и дорого, если рука ухоженная, а покрытие зеркально ровное.",
        "colors": ["черный", "золотой"],
        "style": "гламурный рок",
        "tags": ["пирсинг ногтя", "черный", "кольцо", "новинка 2026", "рок"],
        "color": "черный",
        "complexity": "сложно",
        "shape": "стилет",
        "length": "длинные",
        "techniques": ["твёрдый гель", "сверление", "черный гель-лак", "металлический декор"],
        "design_category": "пирсинг ногтя",
        "timeMinutes": 130,
        "masterGuide": "\n".join([
            "1. Наращивание или укрепление твёрдым гелем, длинная форма стилет или острый миндаль — на короткой пластине пирсинг не держат.",
            "2. Идеально выровнять архитектуру, просушить.",
            "3. Два слоя чёрного гель-лака + глянцевый топ, зеркальная поверхность.",
            "4. Пирсинг делает только мастер: отверстие сверлят в искусственном материале у свободного края, не в живой пластине.",
            "5. Края отверстия зашлифовать, чтобы металл не травмировал.",
            "6. Вставить мини-кольцо из гипоаллергенного металла, застегнуть.",
            "7. Для домашнего эффекта без сверления: два крошечных кафира по бокам ногтя имитируют вход и выход серьги.",
            "8. Проверить, что кольцо не болтается и не цепляет волосы.",
            "9. Топом пройтись вокруг зоны крепления, не заливая сам металл.",
            "10. Кутикула влажная, кожа без сухости — иначе рок-жест выглядит неряшливо.",
        ]),
        "prompt": "Ultra-photoreal salon manicure, extra-long glossy jet-black stiletto nails. One accent nail has a tiny realistic yellow-gold hoop piercing through the free edge like an earring. Mirror shine, perfectly groomed moisturized skin, no dry cuticles. Macro beauty campaign, real woman's hand, exactly five fingers.",
    },
    {
        "n": 114,
        "description": "Blown-glass 2026: ногти как выдувное стекло — прозрачно-хрустальные, с голографическими бликами и лёгкой 3D-скульптурой. Не просто «стеклянный блеск», а ощущение тонкой вазы Baccarat на кончиках. Очень светлый, чистый, ультрареалистичный салонный кадр.",
        "colors": ["прозрачный", "голографический", "ледяной", "серебряный"],
        "style": "стеклянный",
        "tags": ["blown glass", "стекло", "3D", "голография", "новинка 2026"],
        "color": "прозрачный",
        "complexity": "сложно",
        "shape": "миндаль",
        "length": "длинные",
        "techniques": ["builder gel 3D", "хром по прозрачному", "аквариум", "голографическая втирка"],
        "design_category": "выдувное стекло",
        "timeMinutes": 140,
        "masterGuide": "\n".join([
            "1. Длинный миндаль, тонкий свободный край, идеальная кутикула.",
            "2. Прозрачное или молочно-прозрачное выравнивание builder-гелем.",
            "3. Скульптурой из твёрдого геля вылепите лёгкие 3D-волны или капли, как выдувное стекло.",
            "4. Просушите объём, не оставляя пор и пузырей.",
            "5. На липкий слой втрите тончайшую голографическую или кристальную втирку — только блик, не плотный металл.",
            "6. Альтернатива: слой Nail Glow / прозрачный шиммер вместо втирки.",
            "7. Топ без липкого слоя, очень глянцевый, «мокрый».",
            "8. Не перекрывайте объём толстым топом — грани стекла должны читаться.",
            "9. Запечатайте торцы.",
            "10. Масло + полировка кожи: стекло выглядит люксово только на ухоженной руке.",
        ]),
        "prompt": "Ultra-photoreal salon manicure, long almond nails that look like blown glass sculptures: crystal-clear builder gel, holographic light, 3D glass ripples, Baccarat-like transparency. Wet glossy finish, living moisturized skin, perfect cuticles. Macro Vogue beauty, real hand, five fingers, no plastic CGI.",
    },
    {
        "n": 115,
        "description": "Бархатный кошачий глаз 2026: изумрудный магнитный гель с рассеянным свечением, как мнутый бархат, а не одна резкая полоса. Глубокий ювелирный цвет двигается при повороте руки. Тихая роскошь для вечера и для «дорогого повседневного».",
        "colors": ["изумрудный", "зеленый", "черный"],
        "style": "бархатный магнитный",
        "tags": ["velvet cat eye", "бархат", "кошачий глаз", "изумруд", "новинка 2026"],
        "color": "изумрудный",
        "complexity": "средне",
        "shape": "миндаль",
        "length": "длинные",
        "techniques": ["магнитный гель", "velvet-техника", "тёмная подложка"],
        "design_category": "бархатный кошачий глаз",
        "timeMinutes": 70,
        "masterGuide": "\n".join([
            "1. Миндаль средней-длинной длины, идеальная кутикула.",
            "2. Чёрная или очень тёмно-зелёная подложка в 1–2 слоя, просушка.",
            "3. Нанесите плотный магнитный гель изумрудного оттенка.",
            "4. Не держите магнит в одной точке: ведите его по периметру ногтя, рассеивая пигмент.",
            "5. Цель — мягкое бархатное свечение по всей пластине, без лазерной полосы.",
            "6. Быстрая просушка, чтобы частицы не «уплыли».",
            "7. При необходимости второй тонкий слой магнита и повторная проходка.",
            "8. Топ без липкого слоя, не мутный.",
            "9. Запечатайте торцы.",
            "10. Масло на кутикулу: бархат «съедает» свет, если кожа сухая.",
        ]),
        "prompt": "Ultra-photoreal salon manicure, long almond nails in deep emerald velvet cat-eye magnetic gel. Diffused crushed-velvet shimmer across the whole nail, not a sharp cat-eye stripe. Mirror-adjacent gloss, jewel-tone depth, perfectly groomed moisturized hands. Macro beauty campaign, five real fingers.",
    },
    {
        "n": 116,
        "description": "Твид как у Chanel: бежево-кремовая база и тонкая тканевая клетка — нити чёрного, молочного и едва заметного золота. Текстильный маникюр 2026: выглядит сшитым, а не нарисованным. Идеален к жакету, пальто и спокойному городскому образу.",
        "colors": ["бежевый", "кремовый", "черный", "золотой"],
        "style": "текстильный",
        "tags": ["твид", "шанель", "клетка", "текстура", "новинка 2026"],
        "color": "бежевый",
        "complexity": "сложно",
        "shape": "мягкий квадрат",
        "length": "средние",
        "techniques": ["тонкая кисть", "текстильный принт", "микро-шиммер"],
        "design_category": "твид",
        "timeMinutes": 110,
        "masterGuide": "\n".join([
            "1. Форма мягкий квадрат средней длины — твид лучше читается на широкой пластине.",
            "2. Бежево-кремовая непрозрачная подложка, просушка.",
            "3. Тончайшей кистью нарисуйте вертикальные нити чёрного и молочного с неравным шагом, как в ткани.",
            "4. Пересеките горизонтальными нитями той же толщины.",
            "5. В узлах клетки поставьте микроточки золотого шиммера — имитация люрекса.",
            "6. Не делайте идеальную школьную тетрадь: лёгкая «небрежность нити» даёт эффект твида.",
            "7. Просушите рисунок.",
            "8. Глянцевый или полуглянцевый топ — слишком мокрый глянец убивает текстиль.",
            "9. Запечатайте торцы.",
            "10. Кутикула чистая, кожа увлажнённая.",
        ]),
        "prompt": "Ultra-photoreal salon manicure, medium squoval nails painted as Chanel-inspired tweed: beige cream base, fine black and ivory woven threads, tiny gold lurex flecks. Textile nail art, tailored not childish. Perfectly groomed moisturized hands. Macro beauty photo, five real fingers.",
    },
    {
        "n": 117,
        "description": "Gem nails весны 2026: спокойная бежевая база и россыпь мелких разноцветных кристаллов — у кутикулы, на кончике, иногда кустом из двух-трёх камней. Ностальгия и высокий глянец одновременно: как ювелирка, а не детский «bedazzler».",
        "colors": ["бежевый", "нюд", "разноцветный", "серебряный"],
        "style": "инкрустация",
        "tags": ["gem nails", "стразы", "россыпь", "нюд", "новинка 2026"],
        "color": "бежевый",
        "complexity": "средне",
        "shape": "миндаль",
        "length": "длинные",
        "techniques": ["инкрустация", "гель-клей", "нюдовая база"],
        "design_category": "россыпь кристаллов",
        "timeMinutes": 100,
        "masterGuide": "\n".join([
            "1. Длинный миндаль, идеально зачищенная кутикула.",
            "2. Бежево-нюдовый гель-лак в 2 слоя + тонкий топ.",
            "3. Профессиональный клей для страз, не сырой цветной гель.",
            "4. Разложите мелкие камни россыпью: один у кутикулы, один у края, на одном пальце куст из 2–3.",
            "5. Палитра камней радужная, но крошечная — без крупных костюмных страз.",
            "6. Каждый камень каплей геля зафиксируйте у основания.",
            "7. Просушите.",
            "8. Топом обойдите грани, не заливая фасеты.",
            "9. Проверьте ношение: камни не должны сдираться за два дня.",
            "10. Масло на кожу вокруг — нюд + камни работают только на ухоженной руке.",
        ]),
        "prompt": "Ultra-photoreal salon manicure, long almond nails, glossy beige nude base with a refined scatter of tiny rainbow rhinestones: one near cuticle, one at tip, a small cluster on the ring finger. High-fashion gem nails 2026, dainty not costume. Perfect moisturized cuticles. Macro beauty, five real fingers.",
    },
    {
        "n": 118,
        "description": "Лето 2026: объёмные цветы из скульптурного геля — не плоские наклейки, а лепестки, которые почти можно сорвать. Оттенки baby pink, слива и алый вермильон на глянцевой подложке. Цветочный маникюр стал крупнее, мокрее и гораздо более «живым».",
        "colors": ["розовый", "сливовый", "алый", "молочный"],
        "style": "объёмная лепка",
        "tags": ["3D цветы", "лето 2026", "лепка", "гламур", "новинка"],
        "color": "розовый",
        "complexity": "сложно",
        "shape": "миндаль",
        "length": "длинные",
        "techniques": ["3D-лепка", "скульптурный гель", "объёмные цветы"],
        "design_category": "3D цветы",
        "timeMinutes": 150,
        "masterGuide": "\n".join([
            "1. Длинный миндаль, укрепление, молочная или розовая глянцевая подложка.",
            "2. Густым скульптурным гелем вылепите лепестки по одному, начиная с нижнего ряда.",
            "3. Оттенки: нежно-розовый, слива, вермильон — не смешивайте в грязь.",
            "4. Каждый лепесток просушивайте отдельно, чтобы объём не оплыл.",
            "5. Сердцевину обозначьте микробусиной или каплей геля.",
            "6. Не закрывайте всю пластину: 1–2 цветка на акцент, остальные ногти — чистый глянец того же тона.",
            "7. Тонким топом пройдитесь только по подложке, лепестки оставьте с собственным блеском.",
            "8. Проверьте, что цветок не цепляет волосы — высота умеренная.",
            "9. Запечатайте торцы.",
            "10. Кожа вокруг идеально ухоженная, без заусенцев.",
        ]),
        "prompt": "Ultra-photoreal salon manicure, long almond nails. Glossy milky-pink base with hyperrealistic 3D sculpted gel flowers in baby pink, plum and vermillion, petals raised off the nail like freshly plucked blooms. Not flat stickers. Perfect groomed hands, moisturized cuticles. Macro beauty campaign, five real fingers.",
    },
    {
        "n": 119,
        "description": "Двойной финиш лета 2026: кошачий глаз, поверх которого лежит мягкий хром — цвет двигается и переливается, как мокрый металл. Не зеркало 2022 года и не одна магнитная полоса: слоями получается новый оттенок, который «живёт» на свету.",
        "colors": ["сиреневый", "хром", "розовый", "серебряный"],
        "style": "футуристичный",
        "tags": ["хром", "кошачий глаз", "слойка", "новинка 2026", "перелив"],
        "color": "сиреневый",
        "complexity": "средне",
        "shape": "миндаль",
        "length": "длинные",
        "techniques": ["магнитный гель", "втирка хром", "слойка финишей"],
        "design_category": "хром + кошачий глаз",
        "timeMinutes": 80,
        "masterGuide": "\n".join([
            "1. Длинный миндаль, тёмно-сиреневая или пыльно-розовая подложка.",
            "2. Магнитный гель, мягкая бархатная или классическая полоса — на ваш вкус.",
            "3. Просушите магнит полностью.",
            "4. Тонкий топ без липкого, недолгая просушка 20–30 секунд.",
            "5. Втрите мелкий жемчужный или радужный хром очень тонким слоем.",
            "6. Смахните излишки, чтобы не убить магнитный рисунок.",
            "7. Перекройте топом без липкого слоя.",
            "8. При глухом зеркале снимите хром и повторите тоньше.",
            "9. Запечатайте торцы.",
            "10. Масло на кутикулу, рука должна выглядеть как после салона.",
        ]),
        "prompt": "Ultra-photoreal salon manicure, long almond nails. Layered 2026 finish: lilac-pink cat-eye magnetic gel under a whisper of pearly chrome, iridescent movement, wet metal glow. Not flat mirror, not a single harsh stripe. Perfect moisturized hands. Macro beauty, five real fingers.",
    },
    {
        "n": 120,
        "description": "Аура 2.0: не одно пятно по центру, а многослойная дымка — персик, лиловый и холодный хром, которые перетекают друг в друга. Небесный градиент 2026 года, мягкий и глубокий, без жёстких границ.",
        "colors": ["персиковый", "лиловый", "хром", "молочный"],
        "style": "аура",
        "tags": ["aura 2.0", "градиент", "хром", "дымка", "новинка 2026"],
        "color": "персиковый",
        "complexity": "средне",
        "shape": "миндаль",
        "length": "длинные",
        "techniques": ["аэропуффинг", "многослойный градиент", "тонкий хром"],
        "design_category": "аура-хром",
        "timeMinutes": 90,
        "masterGuide": "\n".join([
            "1. Длинный миндаль, молочная полупрозрачная база.",
            "2. Спонжем или аэропуфом набейте персиковое пятно ближе к кутикуле, не круглым штампом.",
            "3. Вторым слоем добавьте лиловую дымку к свободному краю, границы размойте.",
            "4. Просушите.",
            "5. По желанию едва коснитесь центра жемчужным хромом — только блик.",
            "6. Не оставляйте одну «мишень» по центру — это аура прошлого сезона.",
            "7. Глянцевый топ, мокрый финиш.",
            "8. Проверьте симметрию дымки на всех пальцах: ритм один, пятна живые.",
            "9. Запечатайте торцы.",
            "10. Ухоженная влажная кутикула обязательна: градиент выдаёт любую сухость.",
        ]),
        "prompt": "Ultra-photoreal salon manicure, long almond nails. Aura 2.0: layered peach and lilac haze melting into a whisper of chrome, soft multi-tone glow, no single center halo. Wet gloss, perfectly groomed moisturized hands. Macro beauty campaign, five real fingers.",
    },
]


def main():
    data = json.loads(DATA.read_text(encoding="utf-8"))
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    max_id = max(int(x.get("id") or 0) for x in catalog)
    added = []
    for i, spec in enumerate(DESIGNS):
        n = spec["n"]
        fname = f"STIL-26-{n:03d}.jpg"
        if fname in data:
            print("skip existing", fname)
            continue
        rec = {
            "description": spec["description"],
            "colors": spec["colors"],
            "style": spec["style"],
            "tags": spec["tags"],
            "color": spec["color"],
            "complexity": spec["complexity"],
            "thumb": f"thumb_{n:03d}.jpg",
            "masterGuide": spec["masterGuide"],
            "shape": spec["shape"],
            "length": spec["length"],
            "techniques": spec["techniques"],
            "difficulty": spec["complexity"],
            "timeMinutes": spec["timeMinutes"],
            "presentation": "good",
            "needs_regenerate": False,
            "wow_score": 9,
            "verdict": "wow",
            "design_category": spec["design_category"],
            "wow_factor": 10,
            "addedAt": ADDED,
        }
        data[fname] = rec
        cat_item = {
            "id": max_id + 1 + i,
            "filename": fname,
            "originalPath": f"/nails/all/{fname}",
            "thumbPath": f"/nails/all/thumb_{n:03d}.jpg",
            "source": "stil26",
            "color": spec["color"],
            "colors": spec["colors"],
            "style": spec["style"],
            "complexity": spec["complexity"],
            "tags": spec["tags"],
            "verdict": "wow",
            "wow_factor": 10,
            "design_category": spec["design_category"],
            "shape": spec["shape"],
            "length": spec["length"],
            "description": spec["description"],
            "masterGuide": spec["masterGuide"],
            "difficulty": spec["complexity"],
            "timeMinutes": spec["timeMinutes"],
            "techniques": spec["techniques"],
        }
        catalog.append(cat_item)
        added.append(fname)
    DATA.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    CATALOG.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    prompts = ROOT / "public" / "nails" / "_2026_prompts.json"
    prompts.write_text(
        json.dumps(
            [{"id": f"STIL-26-{s['n']:03d}", "prompt": s["prompt"]} for s in DESIGNS],
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print("added", len(added), "data", len(data), "catalog", len(catalog))
    print("\n".join(added))


if __name__ == "__main__":
    main()
